version: '3.8'

services:
  app:
    build:
      context: .  # Lokasi Dockerfile (root proyek)
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Pemetaan port antara host dan container
    environment:
      NODE_ENV: production
      REDIS_HOST: redis  # Nama service Redis dalam docker-compose
      REDIS_PORT: 6379
      # AUTH_DIR: /app/secrets  # Path ke direktori autentikasi di dalam container
    command: ["node", "dist/index.js"]
    depends_on:
      - redis  # Pastikan aplikasi hanya berjalan setelah Redis siap
    # volumes:
    #   - ./secrets:/app/secrets  # Mount direktori secrets dari host ke container

  redis:
    image: redis:latest  # Gunakan image Redis resmi dari Docker Hub
    ports:
      - "6379:6379"  # Pemetaan port Redis antara host dan container
    volumes:
      - redis_data:/data  # Menyimpan data Redis di volume persisten
    restart: unless-stopped  # Otomatis restart jika container berhenti

volumes:
  redis_data:
    driver: local
